export ARCH := "$(uname -m)"
export OS := "$(uname -s | tr '[:upper:]' '[:lower:]')"

build:
	cargo build --lib --release --locked

gen-python: build
	cargo run --bin uniffi-bindgen generate --library target/release/libflorestad_ffi.so --language python --out-dir generated/python --no-format

gen-tar: gen-python
	cp target/release/libflorestad_ffi.so generated/python/libuniffi_floresta.so
	tar cf "{{ARCH}}-{{OS}}.tar" generated/python/floresta.py generated/python/libuniffi_floresta.so

gen-kotlin: build
	cargo run --bin uniffi-bindgen generate --library target/release/libflorestad_ffi.so --language kotlin --out-dir generated/kotlin/ --no-format
